"""Lattice model and loader.

The YAML lattice file (pip2va/lattice/pip2_lattice.yaml, generated by
scripts/gen_lattice.py) is the single source of truth for machine geometry,
design settings, and instrument placement. All services and the GUI load it
through this module.
"""
from __future__ import annotations

from functools import lru_cache
from importlib import resources
from pathlib import Path

import yaml
from pydantic import BaseModel, Field

ELEMENT_TYPES = {
    "drift", "solenoid", "quad", "corrector", "rfgap", "rfq", "chopper",
    "aperture", "dipole", "bpm", "blm", "toroid", "wire_scanner", "source",
}


class Element(BaseModel):
    name: str
    type: str
    s: float                    # entrance position [m]
    length: float = 0.0         # [m]
    section: str
    aperture_radius: float = 0.02   # [m]
    params: dict = Field(default_factory=dict)
    knobs: dict[str, str] = Field(default_factory=dict)  # knob -> settings hash key


class Section(BaseModel):
    name: str
    s_start: float
    s_end: float
    w_in: float                 # design kinetic energy at entrance [MeV]
    w_out: float                # [MeV]
    freq_mhz: float | None = None


class Lattice(BaseModel):
    meta: dict
    sections: list[Section]
    elements: list[Element]

    @property
    def total_length(self) -> float:
        last = self.elements[-1]
        return last.s + last.length

    def instruments(self, typ: str) -> list[Element]:
        return [e for e in self.elements if e.type == typ]

    def by_name(self, name: str) -> Element:
        return self._index()[name]

    def _index(self) -> dict[str, Element]:
        if not hasattr(self, "_idx"):
            object.__setattr__(self, "_idx", {e.name: e for e in self.elements})
        return self._idx

    def section(self, name: str) -> Section:
        return next(s for s in self.sections if s.name == name)


@lru_cache(maxsize=4)
def load_errors(path: str | None = None) -> dict:
    """Static machine imperfections {element: {dx, dy | offset_*, scale}}.

    Returns {} when no errors file exists or PIP2VA_ERRORS=0 (the 'perfect
    machine' used by physics unit tests)."""
    import os
    if os.environ.get("PIP2VA_ERRORS", "1") in ("0", "false"):
        return {}
    if path is None:
        ref = resources.files("pip2va.lattice") / "errors.yaml"
        try:
            raw = ref.read_text()
        except FileNotFoundError:
            return {}
    else:
        raw = Path(path).read_text()
    return yaml.safe_load(raw).get("errors", {})


@lru_cache(maxsize=4)
def load_lattice(path: str | None = None) -> Lattice:
    if path is None:
        ref = resources.files("pip2va.lattice") / "pip2_lattice.yaml"
        raw = ref.read_text()
    else:
        raw = Path(path).read_text()
    doc = yaml.safe_load(raw)
    lat = Lattice(**doc)
    unknown = {e.type for e in lat.elements} - ELEMENT_TYPES
    if unknown:
        raise ValueError(f"unknown element types in lattice: {unknown}")
    return lat
